server:
  port: 8080

spring:
  datasource:
    hikari:
      username: newuser
      password: cs12345678!!
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://61.84.24.210:3306/caps?serverTimezone=UTC&characterEncoding=UTF-8
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: sccPool
      auto-commit: false

#html 컨버터를 Gson으로 설정
  mvc:
    converters:
      preferred-json-mapper: gson

#메일 의존성 주입
  mail:
    host: smtp.gmail.com
    port: 587
    username: geostarboy@gmail.com #구글 아이디
    password: "lsd6974;;;"      #큰따옴표안에 구글 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 서버 자동 리로드
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false

custom:
  path:
    upload-images: 'file:///c:/fileUpload/images/'
